### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by KamalKaur** [Colorless-Green-Ideas/MaterialDjango#14]
HI Jack Laxson,

Having a basic idea about Polymer, I just want to know how can I use these efforts done on MaterialDjango into my Django project?

**Comment by jrabbit** [comment]
I've added some "getting started" type docs to the readme and there's a form example here: http://tech.getpizza.cat/django/update/tinylibrary/shipit/2015/04/10/MaterialDjango-and-tinylibrary/ (disregard the modelform factory example though it's incorrect)

is that helpful?

**Comment by jrabbit** [comment]
let me know if you need anything further
